version: '3'
services:
  zipkin:
    image: openzipkin/zipkin:2.24
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
  collector:
    image: otel/opentelemetry-collector-contrib:0.90.1
    command: ['--config=/etc/otel-collector-config.yaml']
    volumes:
      - ./otel-collector-config-app-insights.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - zipkin
  api-gateway:
    image: nginx-plus:r29
    ports:
      - "8080:80"
    volumes:
      - ./api-gtw/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - collector
      - backend
  backend:
    image: nginx-plus:r29
    ports:
      - "8081:80"
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - collector