receivers:
  otlp:
    protocols:
      grpc:
      http:
  otlp/2:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55690
exporters:
#  jaeger:
#    endpoint: jaeger:14250
#    tls:
#      insecure: true
#  jaeger:
#    endpoint: "http://jaeger:14268/api/traces"
#    insecure: true

  zipkin/nontls:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto
    default_service_name: default-service

#  azuremonitor:
#    instrumentation_key: "c89957ea-387f-4ee3-8170-a6715bb33932"
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin/nontls]
      #, azuremonitor